### ISSUE TITLE
Cleaning all the legacy code

### ISSUE THREAD

**Issue by RolfJens** [course-dprep/The_impact_of_Airbnb_hosts_on_guest_reviews#39]
We have now added 2 functions in this code. But now, the code looks a litte unreadable. Therefore, we can adjust the code as following:

1. **Get rid of unneceserry code:** The only thing that needs to be kept (above the funactions) is the step where the url's are defined and the packages are imported. 
2. **Get rid of the examples for the functions:** After the two functions, I provided an example how to use the function. If everyone understands the function, we can get rid of the examples. 
3. **Give an appropriate name** to the file in stead of 'Tutorial_Making_Dataset_France_Greece.R'

Kind regards,
Rolf

**Comment by JulianPetersIsCoding** [comment]
Hey Rolf,

I will try to enhance the section where we hardcode the url as variables. It is probably possible to webscrape this url. Hence i will be trying this, to fully automate our process. This makes it possible in the future to call for the url's with a makefile. 

Kind regards,

Julian Peters

**Comment by RolfJens** [comment]
Hi Julian,

In the meantime, i worked on the issue to resolve the double file writing (issue #49). When fixing this issue, I also created a new R script where the code already looks a lot cleaner (I had to do this in order to resolve the file writing issue). 

Some cleaning tasks can still be fulfilled, like picking appropriate names.

Feel free to ask for help and happy coding!

Rolf
