### ISSUE TITLE
Replace read.csv with read_csv

### ISSUE THREAD

**Issue by RolfJens** [course-dprep/The_impact_of_Airbnb_hosts_on_guest_reviews#71]
We are currently using the read.csv function in R. Replace this with the read_csv function from the tidyverse library. Do this for all instances pleace (same accounts for the write.csv function)

**Comment by JulianPetersIsCoding** [comment]
Hey Rolf,

We will check this coming Friday.

Kind regards,

Julian Peters

**Comment by RolfJens** [comment]
We have fixed this together and pushed it to another branch. Hence, no pull request has been made for this issue.
